version: '3.1'

services:
  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: card_data
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: qwer1234
    ports:
    - 3306:3306
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
